### POST transactions
POST http://localhost:3333/transactions
content-type: application/json

{
    "title": "request",
    "type": "credit",
    "amount": 1000
}

### LIST transactions
GET http://localhost:3333/transactions


### GET transaction by id
GET http://localhost:3333/transactions/4af67436-422d-4345-b240-a02e132a2695